### ISSUE TITLE
Fix or silence build warning

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/tonic-ui#5]
This may be harmless but it is unsettling to see this on the `npm run build` step on master:

```
WARNING in ./lib/native/infoviz/ParallelCoords/index.js

/Users/jeff/code/tonic-ui/lib/native/infoviz/ParallelCoords/index.js
  413:13  warning  "fetchHistograms" was used before it was defined  no-use-before-define
```

**Comment by jourdain** [comment]
I agree, but that should be fixed by the code owner/contributor. I fixed Roni's ones the other day. 
That one is own by Scott, but he left for KRS this week and only learned how to fix it last Friday evening.

So I'm just waiting for him to come back, as I rather teach each developer how to fix their code rather than fixing it for everyone. ;-)
